import { Incident } from '../types/incident';
import { UserProfile } from '../types/user';
import { ActivityLog } from '../types/activity';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'admin-001',
    name: 'Dr. Rajesh Mohanty',
    email: 'admin@campusresq.edu',
    role: 'admin',
    department: 'Campus Safety & Emergency Operations',
    phoneNumber: '+91 98765 43210',
    status: 'active',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'mentor-101',
    name: 'Prof. Ananya Sen',
    email: 'ananya.sen@campusresq.edu',
    role: 'mentor',
    department: 'School of Computer Engineering',
    phoneNumber: '+91 98765 11223',
    status: 'active',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'mentor-102',
    name: 'Dr. Vikramaditya Rao',
    email: 'vikram.rao@campusresq.edu',
    role: 'mentor',
    department: 'Hostel Administration & Welfare',
    phoneNumber: '+91 98765 22334',
    status: 'active',
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'mentor-103',
    name: 'Capt. Suresh Panda',
    email: 'suresh.panda@campusresq.edu',
    role: 'mentor',
    department: 'Campus Security Quick Response',
    phoneNumber: '+91 98765 33445',
    status: 'active',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'student-201',
    name: 'Priya Sharma',
    email: 'priya.2105123@campusresq.edu',
    role: 'student',
    department: 'B.Tech CSE - 3rd Year',
    phoneNumber: '+91 98111 22334',
    status: 'active',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'student-202',
    name: 'Arjun Das',
    email: 'arjun.2205456@campusresq.edu',
    role: 'student',
    department: 'B.Tech IT - 2nd Year',
    phoneNumber: '+91 98222 33445',
    status: 'active',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'student-203',
    name: 'Rohan Mehra',
    email: 'rohan.2305789@campusresq.edu',
    role: 'student',
    department: 'B.Tech Mechanical - 1st Year',
    phoneNumber: '+91 98333 44556',
    status: 'active',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  }
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-2026-001',
    title: 'Severe Asthma Attack & Respiratory Distress',
    description: 'Student collapsed outside Central Library 2nd floor study hall experiencing severe breathing difficulty. First aid team requested immediately.',
    category: 'medical',
    severity: 'critical',
    status: 'in_progress',
    location: {
      latitude: 20.3533,
      longitude: 85.8189,
      address: 'Central Library, 2nd Floor, West Wing',
      building: 'Central Library',
      floor: '2nd Floor',
    },
    reporterId: 'student-201',
    reporterName: 'Priya Sharma',
    reporterEmail: 'priya.2105123@campusresq.edu',
    reporterPhone: '+91 98111 22334',
    assignedTo: 'mentor-103',
    assignedToName: 'Capt. Suresh Panda',
    assignedToEmail: 'suresh.panda@campusresq.edu',
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-002',
    title: 'Smoke Detected in Chemistry Lab 3 Exhaust System',
    description: 'Chemical odor and thick grey smoke emerging from fume hood in Organic Chem Lab 304. Lab evacuated.',
    category: 'fire',
    severity: 'high',
    status: 'assigned',
    location: {
      latitude: 20.3545,
      longitude: 85.8201,
      address: 'School of Applied Sciences, Block C, Room 304',
      building: 'Science Complex Block C',
      floor: '3rd Floor',
    },
    reporterId: 'student-202',
    reporterName: 'Arjun Das',
    reporterEmail: 'arjun.2205456@campusresq.edu',
    reporterPhone: '+91 98222 33445',
    assignedTo: 'mentor-101',
    assignedToName: 'Prof. Ananya Sen',
    assignedToEmail: 'ananya.sen@campusresq.edu',
    createdAt: new Date(Date.now() - 75 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-003',
    title: 'Intimidation & Ragging Complaint at Boys Hostel 7',
    description: 'Freshers reported unauthorized gathering and forceful late-night room entry by senior group on 4th floor.',
    category: 'ragging',
    severity: 'high',
    status: 'reported',
    location: {
      latitude: 20.3512,
      longitude: 85.8155,
      address: 'King Fisher Hostel (KP-7), Wing B, 4th Floor',
      building: 'Hostel KP-7',
      floor: '4th Floor',
    },
    reporterId: 'student-203',
    reporterName: 'Rohan Mehra',
    reporterEmail: 'rohan.2305789@campusresq.edu',
    reporterPhone: '+91 98333 44556',
    assignedTo: null,
    assignedToName: null,
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-004',
    title: 'Main Gate Access Barrier Malfunction & Traffic Snarl',
    description: 'Automated RFID boom barrier stuck down, causing severe vehicle backlog onto public highway.',
    category: 'facility',
    severity: 'medium',
    status: 'in_progress',
    location: {
      latitude: 20.3562,
      longitude: 85.8225,
      address: 'Campus Gate 3 (Medical College Entrance)',
      building: 'Security Gate Complex 3',
      floor: 'Ground',
    },
    reporterId: 'student-201',
    reporterName: 'Priya Sharma',
    reporterEmail: 'priya.2105123@campusresq.edu',
    assignedTo: 'mentor-103',
    assignedToName: 'Capt. Suresh Panda',
    assignedToEmail: 'suresh.panda@campusresq.edu',
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-005',
    title: 'Electrical Sparking in Server Room AC Unit',
    description: 'Continuous sparking and burning smell from 5-ton split AC outdoor unit on roof of Data Center.',
    category: 'facility',
    severity: 'critical',
    status: 'resolved',
    location: {
      latitude: 20.3528,
      longitude: 85.8174,
      address: 'Central IT Center, Rooftop Server Unit',
      building: 'Data Center Building',
      floor: 'Rooftop',
    },
    reporterId: 'mentor-101',
    reporterName: 'Prof. Ananya Sen',
    reporterEmail: 'ananya.sen@campusresq.edu',
    assignedTo: 'mentor-102',
    assignedToName: 'Dr. Vikramaditya Rao',
    assignedToEmail: 'vikram.rao@campusresq.edu',
    resolutionNotes: 'Technician replaced faulty capacitor and rewired contactor relay. Thermal imaging confirmed normal temperature.',
    resolvedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    createdAt: new Date(Date.now() - 360 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-006',
    title: 'Sports Complex Knee Injury during Basketball League',
    description: 'Student twisted left knee with audible pop and cannot bear weight. Ice pack applied, stretcher dispatched.',
    category: 'medical',
    severity: 'medium',
    status: 'resolved',
    location: {
      latitude: 20.3498,
      longitude: 85.8142,
      address: 'Indoor Stadium Basketball Court 1',
      building: 'KIMS Indoor Stadium',
      floor: 'Ground',
    },
    reporterId: 'student-202',
    reporterName: 'Arjun Das',
    reporterEmail: 'arjun.2205456@campusresq.edu',
    assignedTo: 'mentor-103',
    assignedToName: 'Capt. Suresh Panda',
    resolutionNotes: 'Transported to Campus Health Center via ambulance. Ligament strain diagnosed, brace fitted, discharged with pain medication.',
    resolvedAt: new Date(Date.now() - 120 * 60000).toISOString(),
    createdAt: new Date(Date.now() - 480 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 60000).toISOString(),
  }
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-001',
    incidentId: 'inc-2026-003',
    action: 'INCIDENT_CREATED',
    performedBy: 'student-203',
    performedByName: 'Rohan Mehra',
    performedByRole: 'student',
    details: 'New high severity incident reported: Intimidation & Ragging Complaint at Boys Hostel 7',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'log-002',
    incidentId: 'inc-2026-001',
    action: 'INCIDENT_ASSIGNED',
    performedBy: 'admin-001',
    performedByName: 'Dr. Rajesh Mohanty',
    performedByRole: 'admin',
    details: 'Assigned incident to Capt. Suresh Panda (Campus Security Quick Response)',
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    id: 'log-003',
    incidentId: 'inc-2026-001',
    action: 'STATUS_CHANGED',
    performedBy: 'mentor-103',
    performedByName: 'Capt. Suresh Panda',
    performedByRole: 'mentor',
    details: 'Status changed from "assigned" to "in_progress". First responder dispatched.',
    timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'log-004',
    incidentId: 'inc-2026-002',
    action: 'INCIDENT_ASSIGNED',
    performedBy: 'admin-001',
    performedByName: 'Dr. Rajesh Mohanty',
    performedByRole: 'admin',
    details: 'Assigned incident to Prof. Ananya Sen (School of Computer Engineering)',
    timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  {
    id: 'log-005',
    incidentId: 'inc-2026-005',
    action: 'INCIDENT_RESOLVED',
    performedBy: 'mentor-102',
    performedByName: 'Dr. Vikramaditya Rao',
    performedByRole: 'mentor',
    details: 'Marked resolved: Electrical short-circuit in Server Room AC Unit repaired.',
    timestamp: new Date(Date.now() - 40 * 60000).toISOString(),
  }
];
