import { Incident } from '../types/incident';
import { UserProfile } from '../types/user';
import { ActivityLog } from '../types/activity';
import { CampusAlert } from '../types/alert';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'admin-001',
    name: 'Dr. Rajesh Mohanty',
    email: 'admin@campusresq.edu',
    role: 'admin',
    department: 'Campus Safety & Emergency Operations',
    phoneNumber: '+91 98765 43210',
    status: 'active',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'mentor-101',
    name: 'Prof. Ananya Sen',
    email: 'ananya.sen@campusresq.edu',
    role: 'mentor',
    department: 'School of Computer Engineering',
    phoneNumber: '+91 98765 11223',
    status: 'active',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'mentor-102',
    name: 'Dr. Vikramaditya Rao',
    email: 'vikram.rao@campusresq.edu',
    role: 'mentor',
    department: 'Hostel Administration & Welfare',
    phoneNumber: '+91 98765 22334',
    status: 'active',
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'mentor-103',
    name: 'Capt. Suresh Panda',
    email: 'suresh.panda@campusresq.edu',
    role: 'mentor',
    department: 'Campus Security Quick Response Team',
    phoneNumber: '+91 98765 33445',
    status: 'active',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'student-201',
    name: 'Priya Sharma',
    email: 'priya.2105123@campusresq.edu',
    role: 'student',
    department: 'B.Tech CSE - 3rd Year',
    phoneNumber: '+91 98111 22334',
    status: 'active',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'student-202',
    name: 'Arjun Das',
    email: 'arjun.2205456@campusresq.edu',
    role: 'student',
    department: 'B.Tech IT - 2nd Year',
    phoneNumber: '+91 98222 33445',
    status: 'active',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'student-203',
    name: 'Rohan Mehra',
    email: 'rohan.2305789@campusresq.edu',
    role: 'student',
    department: 'B.Tech Mechanical - 1st Year',
    phoneNumber: '+91 98333 44556',
    status: 'active',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  }
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-2026-001',
    title: 'Severe Asthma Attack & Respiratory Distress',
    description: 'Student collapsed outside Central Library 2nd floor study hall experiencing acute breathing difficulty. Emergency medical response requested immediately.',
    category: 'medical',
    severity: 'critical',
    status: 'in_progress',
    location: {
      latitude: 20.3533,
      longitude: 85.8189,
      address: 'Central Library, 2nd Floor, West Wing',
      building: 'Central Library',
      floor: '2nd Floor',
    },
    reporterId: 'student-201',
    reporterName: 'Priya Sharma',
    reporterEmail: 'priya.2105123@campusresq.edu',
    reporterPhone: '+91 98111 22334',
    isAnonymous: false,
    assignedTo: 'mentor-103',
    assignedToName: 'Capt. Suresh Panda',
    assignedToEmail: 'suresh.panda@campusresq.edu',
    assignedToPhone: '+91 98765 33445',
    images: ['https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80'],
    evidence: [
      {
        id: 'ev-001',
        name: 'library_hall_location.jpg',
        url: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80',
        size: 1420000,
        mimeType: 'image/jpeg',
        uploadedAt: new Date(Date.now() - 25 * 60000).toISOString(),
      }
    ],
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(), // 25 mins ago
    assignedAt: new Date(Date.now() - 20 * 60000).toISOString(), // 5 min response time
    inProgressAt: new Date(Date.now() - 10 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-002',
    title: 'Smoke Detected in Chemistry Lab 3 Exhaust System',
    description: 'Chemical odor and grey smoke emerging from fume hood in Organic Chem Lab 304. Lab evacuated.',
    category: 'fire',
    severity: 'high',
    status: 'assigned',
    location: {
      latitude: 20.3545,
      longitude: 85.8201,
      address: 'School of Applied Sciences, Block C, Room 304',
      building: 'Science Complex Block C',
      floor: '3rd Floor',
    },
    reporterId: 'student-202',
    reporterName: 'Arjun Das',
    reporterEmail: 'arjun.2205456@campusresq.edu',
    reporterPhone: '+91 98222 33445',
    isAnonymous: false,
    assignedTo: 'mentor-101',
    assignedToName: 'Prof. Ananya Sen',
    assignedToEmail: 'ananya.sen@campusresq.edu',
    assignedToPhone: '+91 98765 11223',
    images: ['https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=600&q=80'],
    evidence: [
      {
        id: 'ev-002',
        name: 'chem_lab_vent_smoke.jpg',
        url: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=600&q=80',
        size: 2150000,
        mimeType: 'image/jpeg',
        uploadedAt: new Date(Date.now() - 75 * 60000).toISOString(),
      }
    ],
    createdAt: new Date(Date.now() - 75 * 60000).toISOString(), // 75 mins ago
    assignedAt: new Date(Date.now() - 65 * 60000).toISOString(), // 10 min response time
    updatedAt: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-003',
    title: 'Intimidation & Ragging Complaint at Boys Hostel 7',
    description: 'Freshers reported unauthorized gathering and forceful late-night room entry by senior group on 4th floor.',
    category: 'ragging',
    severity: 'high',
    status: 'reported',
    location: {
      latitude: 20.3512,
      longitude: 85.8155,
      address: 'King Fisher Hostel (KP-7), Wing B, 4th Floor',
      building: 'Hostel KP-7',
      floor: '4th Floor',
    },
    reporterId: 'student-203',
    reporterName: 'Anonymous Reporter',
    reporterEmail: undefined,
    reporterPhone: undefined,
    isAnonymous: true,
    assignedTo: null,
    assignedToName: null,
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-004',
    title: 'Main Gate Access Barrier Malfunction & Traffic Snarl',
    description: 'Automated RFID boom barrier stuck down, causing severe vehicle backlog onto public highway.',
    category: 'facility',
    severity: 'medium',
    status: 'in_progress',
    location: {
      latitude: 20.3562,
      longitude: 85.8225,
      address: 'Campus Gate 3 (Medical College Entrance)',
      building: 'Security Gate Complex 3',
      floor: 'Ground',
    },
    reporterId: 'student-201',
    reporterName: 'Priya Sharma',
    reporterEmail: 'priya.2105123@campusresq.edu',
    isAnonymous: false,
    assignedTo: 'mentor-103',
    assignedToName: 'Capt. Suresh Panda',
    assignedToEmail: 'suresh.panda@campusresq.edu',
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    assignedAt: new Date(Date.now() - 165 * 60000).toISOString(), // 15 min response time
    inProgressAt: new Date(Date.now() - 60 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-005',
    title: 'Electrical Sparking in Server Room AC Unit',
    description: 'Continuous sparking and burning smell from 5-ton split AC outdoor unit on roof of Data Center.',
    category: 'facility',
    severity: 'critical',
    status: 'resolved',
    location: {
      latitude: 20.3528,
      longitude: 85.8174,
      address: 'Central IT Center, Rooftop Server Unit',
      building: 'Data Center Building',
      floor: 'Rooftop',
    },
    reporterId: 'mentor-101',
    reporterName: 'Prof. Ananya Sen',
    reporterEmail: 'ananya.sen@campusresq.edu',
    isAnonymous: false,
    assignedTo: 'mentor-102',
    assignedToName: 'Dr. Vikramaditya Rao',
    assignedToEmail: 'vikram.rao@campusresq.edu',
    resolutionNotes: 'Technician replaced faulty capacitor and rewired contactor relay. Thermal imaging confirmed normal temperature.',
    createdAt: new Date(Date.now() - 360 * 60000).toISOString(),
    assignedAt: new Date(Date.now() - 352 * 60000).toISOString(), // 8 min response time
    resolvedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-006',
    title: 'Sports Complex Knee Injury during Basketball League',
    description: 'Student twisted left knee with audible pop and cannot bear weight. Ice pack applied, stretcher dispatched.',
    category: 'medical',
    severity: 'medium',
    status: 'resolved',
    location: {
      latitude: 20.3498,
      longitude: 85.8142,
      address: 'Indoor Stadium Basketball Court 1',
      building: 'KIMS Indoor Stadium',
      floor: 'Ground',
    },
    reporterId: 'student-202',
    reporterName: 'Arjun Das',
    reporterEmail: 'arjun.2205456@campusresq.edu',
    isAnonymous: false,
    assignedTo: 'mentor-103',
    assignedToName: 'Capt. Suresh Panda',
    assignedToEmail: 'suresh.panda@campusresq.edu',
    resolutionNotes: 'Transported to Campus Health Center via ambulance. Ligament strain diagnosed, brace fitted, discharged with pain medication.',
    createdAt: new Date(Date.now() - 480 * 60000).toISOString(),
    assignedAt: new Date(Date.now() - 468 * 60000).toISOString(), // 12 min response time
    resolvedAt: new Date(Date.now() - 120 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-007',
    title: 'Unlit Pathway & Stalker Sighting near KP-7 Hostel Boundary',
    description: 'Two students reported a trespasser near the unlit perimeter fence behind KP-7 Boys Hostel.',
    category: 'security',
    severity: 'high',
    status: 'resolved',
    location: {
      latitude: 20.3515,
      longitude: 85.8152,
      address: 'Perimeter Pathway, Behind KP-7 Hostel',
      building: 'Hostel KP-7',
      floor: 'Ground',
    },
    reporterId: 'student-203',
    reporterName: 'Anonymous Reporter',
    isAnonymous: true,
    assignedTo: 'mentor-103',
    assignedToName: 'Capt. Suresh Panda',
    assignedToEmail: 'suresh.panda@campusresq.edu',
    resolutionNotes: 'Security patrolling increased in perimeter zone. Temporary floodlight deployed.',
    createdAt: new Date(Date.now() - 1440 * 60000).toISOString(), // 24h ago
    assignedAt: new Date(Date.now() - 1431 * 60000).toISOString(), // 9 min response time
    resolvedAt: new Date(Date.now() - 1200 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 1200 * 60000).toISOString(),
  }
];

export const INITIAL_ALERTS: CampusAlert[] = [
  {
    id: 'alert-2026-001',
    title: 'FLASH FLOOD / WATERLOGGING ADVISORY',
    message: 'Heavy localized rainfall has flooded the low-lying subway connecting Campus 3 and Campus 11. Use the foot overbridge until water recedes.',
    severity: 'warning',
    category: 'weather',
    targetArea: 'Subway Connector (Campus 3 to 11)',
    active: true,
    createdBy: 'admin-001',
    createdByName: 'Dr. Rajesh Mohanty (Campus Ops)',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    expiresAt: new Date(Date.now() + 180 * 60000).toISOString(),
    acknowledgedCount: 342,
  },
  {
    id: 'alert-2026-002',
    title: 'CHEMISTRY COMPLEX VENTILATION MAINTENANCE',
    message: 'Block C organic exhaust maintenance underway. Lab rooms 301-306 strictly closed until 18:00 hrs.',
    severity: 'advisory',
    category: 'facility',
    targetArea: 'Science Complex Block C',
    active: true,
    createdBy: 'admin-001',
    createdByName: 'Dr. Rajesh Mohanty (Campus Ops)',
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    expiresAt: new Date(Date.now() + 240 * 60000).toISOString(),
    acknowledgedCount: 189,
  }
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-001',
    incidentId: 'inc-2026-003',
    action: 'INCIDENT_CREATED',
    performedBy: 'student-203',
    performedByName: 'Anonymous Reporter',
    performedByRole: 'student',
    details: 'New high severity confidential incident reported: Intimidation & Ragging Complaint at Boys Hostel 7',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'log-002',
    incidentId: 'inc-2026-001',
    action: 'INCIDENT_ASSIGNED',
    performedBy: 'admin-001',
    performedByName: 'Dr. Rajesh Mohanty',
    performedByRole: 'admin',
    details: 'Assigned incident to Capt. Suresh Panda (Campus Security Quick Response)',
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    id: 'log-003',
    incidentId: 'inc-2026-001',
    action: 'STATUS_CHANGED',
    performedBy: 'mentor-103',
    performedByName: 'Capt. Suresh Panda',
    performedByRole: 'mentor',
    details: 'Status changed from "assigned" to "in_progress". First responder on-scene.',
    timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'log-004',
    incidentId: 'inc-2026-002',
    action: 'INCIDENT_ASSIGNED',
    performedBy: 'admin-001',
    performedByName: 'Dr. Rajesh Mohanty',
    performedByRole: 'admin',
    details: 'Assigned incident to Prof. Ananya Sen (School of Computer Engineering)',
    timestamp: new Date(Date.now() - 65 * 60000).toISOString(),
  },
  {
    id: 'log-005',
    incidentId: 'inc-2026-005',
    action: 'INCIDENT_RESOLVED',
    performedBy: 'mentor-102',
    performedByName: 'Dr. Vikramaditya Rao',
    performedByRole: 'mentor',
    details: 'Marked resolved: Electrical short-circuit in Server Room AC Unit repaired.',
    timestamp: new Date(Date.now() - 40 * 60000).toISOString(),
  },
  {
    id: 'log-006',
    action: 'SYSTEM_ALERT',
    performedBy: 'admin-001',
    performedByName: 'Dr. Rajesh Mohanty',
    performedByRole: 'admin',
    details: 'Broadcasted campus safety alert: FLASH FLOOD / WATERLOGGING ADVISORY for Subway Connector',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
  }
];
