import { Incident } from '../types/incident';
import { UserProfile } from '../types/user';
import { ActivityLog } from '../types/activity';
import { CampusAlert } from '../types/alert';

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'admin-001',
    name: 'Dr. Rajesh Mohanty',
    email: 'admin@campusresq.edu',
    role: 'admin',
    department: 'Campus Safety & Operations Command',
    phoneNumber: '+91 98765 43210',
    status: 'active',
    createdAt: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
  {
    id: 'mentor-101',
    name: 'Prof. Ananya Sen',
    email: 'ananya.sen@campusresq.edu',
    role: 'mentor',
    department: 'Quick Response Team Lead',
    phoneNumber: '+91 98765 11223',
    status: 'active',
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'mentor-103',
    name: 'Capt. Suresh Panda',
    email: 'suresh.panda@campusresq.edu',
    role: 'mentor',
    department: 'Campus Security Unit',
    phoneNumber: '+91 98765 33445',
    status: 'active',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'student-201',
    name: 'Priya Sharma',
    email: 'priya.2105123@campusresq.edu',
    role: 'student',
    department: 'School of Engineering',
    phoneNumber: '+91 98111 22334',
    status: 'active',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  }
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'inc-2026-001',
    title: 'Severe Asthma Attack & Respiratory Distress',
    description: 'Student collapsed outside Central Library 2nd floor study hall experiencing acute breathing difficulty. Emergency medical response requested immediately.',
    category: 'medical',
    status: 'in_progress',
    location: {
      latitude: 20.3533,
      longitude: 85.8189,
      address: 'Central Library, 2nd Floor, West Wing',
      building: 'Central Library',
      floor: '2nd Floor',
    },
    reporterId: 'student-201',
    reporterName: 'Priya Sharma',
    isAnonymous: false,
    aiAnalysisStatus: 'completed',
    aiAnalysis: JSON.stringify({
      severity: 'CRITICAL',
      priorityScore: 10,
      summary: 'Acute medical distress requiring immediate on-site oxygen and ambulance dispatch.',
      suggestedAction: 'Dispatch campus medical van with oxygen kit and notify medical team.',
      requiresImmediateResponse: true
    }),
    assignedTo: 'mentor-103',
    assignedToName: 'Capt. Suresh Panda',
    images: ['https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80'],
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    assignedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    inProgressAt: new Date(Date.now() - 10 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-002',
    title: 'Smoke Detected in Chemistry Lab 3 Exhaust System',
    description: 'Chemical odor and grey smoke emerging from fume hood in Organic Chem Lab 304. Lab evacuated.',
    category: 'fire',
    status: 'accepted',
    location: {
      latitude: 20.3545,
      longitude: 85.8201,
      address: 'School of Applied Sciences, Block C, Room 304',
      building: 'Science Complex Block C',
      floor: '3rd Floor',
    },
    reporterId: 'student-202',
    reporterName: 'Arjun Das',
    isAnonymous: false,
    aiAnalysisStatus: 'completed',
    aiAnalysis: JSON.stringify({
      severity: 'HIGH',
      priorityScore: 8,
      summary: 'Potential chemical fume leak and localized fire hazard in laboratory exhaust.',
      suggestedAction: 'Activate building fire alarm, cut gas mains, and dispatch fire safety team.',
      requiresImmediateResponse: true
    }),
    assignedTo: 'mentor-101',
    assignedToName: 'Prof. Ananya Sen',
    images: ['https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=600&q=80'],
    createdAt: new Date(Date.now() - 75 * 60000).toISOString(),
    assignedAt: new Date(Date.now() - 65 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-003',
    title: 'Intimidation & Ragging Complaint at Boys Hostel 7',
    description: 'Freshers reported unauthorized gathering and forceful late-night room entry by senior group on 4th floor.',
    category: 'ragging',
    status: 'pending',
    location: {
      latitude: 20.3512,
      longitude: 85.8155,
      address: 'King Fisher Hostel (KP-7), Wing B, 4th Floor',
      building: 'Hostel KP-7',
      floor: '4th Floor',
    },
    reporterId: 'student-203',
    reporterName: 'Anonymous Reporter',
    isAnonymous: true,
    aiAnalysisStatus: 'completed',
    aiAnalysis: JSON.stringify({
      severity: 'HIGH',
      priorityScore: 7,
      summary: 'High-severity anti-ragging complaint with student intimidation reported in hostel.',
      suggestedAction: 'Dispatch hostel warden and anti-ragging squad immediately.',
      requiresImmediateResponse: false
    }),
    assignedTo: null,
    assignedToName: null,
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-004',
    title: 'Main Gate Access Barrier Malfunction & Vehicle Backlog',
    description: 'Automated RFID boom barrier stuck down, causing vehicle backlog onto highway.',
    category: 'facility',
    status: 'pending',
    location: {
      latitude: 20.3562,
      longitude: 85.8225,
      address: 'Campus Gate 3 (Medical College Entrance)',
      building: 'Security Gate Complex 3',
      floor: 'Ground',
    },
    reporterId: 'student-201',
    reporterName: 'Priya Sharma',
    isAnonymous: false,
    aiAnalysisStatus: 'completed',
    aiAnalysis: {
      severity: 'MEDIUM',
      priorityScore: 4,
      summary: 'Infrastructure failure causing traffic congestion at campus entrance.',
      suggestedAction: 'Switch to manual barrier operation and dispatch technician.',
      requiresImmediateResponse: false
    },
    assignedTo: null,
    assignedToName: null,
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 180 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-005',
    title: 'Electrical Sparking in Server Room AC Unit',
    description: 'Continuous sparking and burning smell from split AC outdoor unit on Data Center roof.',
    category: 'facility',
    status: 'resolved',
    location: {
      latitude: 20.3528,
      longitude: 85.8174,
      address: 'Central IT Center, Rooftop Server Unit',
      building: 'Data Center Building',
      floor: 'Rooftop',
    },
    reporterId: 'mentor-101',
    reporterName: 'Prof. Ananya Sen',
    isAnonymous: false,
    aiAnalysisStatus: 'completed',
    aiAnalysis: JSON.stringify({
      severity: 'CRITICAL',
      priorityScore: 9,
      summary: 'Electrical hazard threatening server room cooling and critical campus infrastructure.',
      suggestedAction: 'Isolate electrical breaker and replace damaged capacitor immediately.',
      requiresImmediateResponse: true
    }),
    assignedTo: 'mentor-103',
    assignedToName: 'Capt. Suresh Panda',
    resolutionNotes: 'Technician replaced faulty capacitor and rewired contactor relay. Thermal imaging confirmed normal operation.',
    createdAt: new Date(Date.now() - 360 * 60000).toISOString(),
    assignedAt: new Date(Date.now() - 352 * 60000).toISOString(),
    resolvedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-006',
    title: 'Sports Complex Knee Injury during Basketball League',
    description: 'Student twisted left knee with audible pop and cannot bear weight. Stretcher dispatched.',
    category: 'medical',
    status: 'resolved',
    location: {
      latitude: 20.3498,
      longitude: 85.8142,
      address: 'Indoor Stadium Basketball Court 1',
      building: 'KIMS Indoor Stadium',
      floor: 'Ground',
    },
    reporterId: 'student-202',
    reporterName: 'Arjun Das',
    isAnonymous: false,
    aiAnalysisStatus: 'completed',
    aiAnalysis: JSON.stringify({
      severity: 'MEDIUM',
      priorityScore: 5,
      summary: 'Moderate sports injury requiring first aid and health center examination.',
      suggestedAction: 'Apply ice compression and transfer to campus health center via wheelchair.',
      requiresImmediateResponse: false
    }),
    assignedTo: 'mentor-103',
    assignedToName: 'Capt. Suresh Panda',
    resolutionNotes: 'Transported to Campus Health Center. Ligament strain diagnosed, brace fitted.',
    createdAt: new Date(Date.now() - 480 * 60000).toISOString(),
    assignedAt: new Date(Date.now() - 468 * 60000).toISOString(),
    resolvedAt: new Date(Date.now() - 120 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 60000).toISOString(),
  },
  {
    id: 'inc-2026-007',
    title: 'Unlit Pathway & Stalker Sighting near KP-7 Hostel Boundary',
    description: 'Two students reported a trespasser near the unlit perimeter fence behind KP-7 Boys Hostel.',
    category: 'security',
    status: 'resolved',
    location: {
      latitude: 20.3515,
      longitude: 85.8152,
      address: 'Perimeter Pathway, Behind KP-7 Hostel',
      building: 'Hostel KP-7',
      floor: 'Ground',
    },
    reporterId: 'student-203',
    reporterName: 'Anonymous Reporter',
    isAnonymous: true,
    aiAnalysisStatus: 'completed',
    aiAnalysis: JSON.stringify({
      severity: 'HIGH',
      priorityScore: 8,
      summary: 'Security vulnerability due to lack of lighting and unauthorized perimeter entry.',
      suggestedAction: 'Deploy security patrol, install floodlight, and reinforce boundary fence.',
      requiresImmediateResponse: false
    }),
    assignedTo: 'mentor-103',
    assignedToName: 'Capt. Suresh Panda',
    resolutionNotes: 'Security patrolling increased in perimeter zone. Temporary floodlight deployed.',
    createdAt: new Date(Date.now() - 1440 * 60000).toISOString(),
    assignedAt: new Date(Date.now() - 1431 * 60000).toISOString(),
    resolvedAt: new Date(Date.now() - 1200 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 1200 * 60000).toISOString(),
  }
];

export const INITIAL_ALERTS: CampusAlert[] = [
  {
    id: 'alert-2026-001',
    title: 'FLASH FLOOD / WATERLOGGING ADVISORY',
    message: 'Heavy localized rainfall has flooded the low-lying subway connecting Campus 3 and Campus 11. Use the foot overbridge until water recedes.',
    severity: 'warning',
    category: 'weather',
    targetArea: 'Subway Connector (Campus 3 to 11)',
    active: true,
    createdBy: 'admin-001',
    createdByName: 'Dr. Rajesh Mohanty (Campus Ops)',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
    expiresAt: new Date(Date.now() + 180 * 60000).toISOString(),
    acknowledgedCount: 342,
  }
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log-001',
    incidentId: 'inc-2026-003',
    action: 'INCIDENT_CREATED',
    performedBy: 'student-203',
    performedByName: 'Anonymous Reporter',
    performedByRole: 'student',
    details: 'New high severity confidential incident reported: Intimidation & Ragging Complaint at Boys Hostel 7',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'log-002',
    incidentId: 'inc-2026-001',
    action: 'INCIDENT_ASSIGNED',
    performedBy: 'admin-001',
    performedByName: 'Dr. Rajesh Mohanty',
    performedByRole: 'admin',
    details: 'Assigned incident to Capt. Suresh Panda',
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    id: 'log-003',
    incidentId: 'inc-2026-001',
    action: 'STATUS_CHANGED',
    performedBy: 'mentor-103',
    performedByName: 'Capt. Suresh Panda',
    performedByRole: 'mentor',
    details: 'Status changed from "assigned" to "in_progress". First responder on-scene.',
    timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
  }
];
